swagger: "2.0"

info: 
  $ref: ./info.yaml

host: "url-shortener.apphb.com"
basePath: "/"

tags: 
  - $ref: ./tags/account.yaml
  - $ref: ./tags/url.yaml

schemes: 
  - "http"

paths: 
  $ref: ./paths/paths.yaml